# Generated by Django 5.0.2 on 2024-03-14 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funeral_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer', models.BooleanField(default=True)),
                ('costume', models.BooleanField(default=True)),
                ('catering', models.BooleanField(default=True)),
                ('freezer', models.BooleanField(default=True)),
                ('coffin', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='funeralbooking',
            name='package_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='funeralbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funeral_bookings', to='funeral_services.user'),
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Death Certificate', 'Death Certificate'), ('Burial Permit', 'Burial Permit'), ('Cremation Authorization Form', 'Cremation Authorization Form')], max_length=100)),
                ('document_file', models.FileField(upload_to='legal_documents/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funeral_services.user')),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
            },
        ),
        migrations.DeleteModel(
            name='LegalDocumentation',
        ),
    ]
