# Generated by Django 5.0.2 on 2024-03-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funeral_services', '0002_service_alter_funeralbooking_package_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='funeral_service_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
