# Generated by Django 5.0.2 on 2024-03-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funeral_services', '0006_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
