# Generated by Django 5.0.2 on 2024-03-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funeral_services', '0010_employee_delete_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
