# Generated by Django 5.0.2 on 2024-03-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funeral_services', '0011_remove_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='staff', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
